### ISSUE TITLE
[Bug] MineMarket plugin ERROR

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#27]
[18:49:22] [Server thread/INFO]: Your target Gida is not online!
[18:49:22] [Server thread/ERROR]: Could not pass event MineMarketPurchaseProcessingEvent to MineMarket-Universal v2.91
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at hu.infinityhosting.bukkit.managers.PurchaseManager$PurchaseProcessor$1$2.run(PurchaseManager.java:262) [MineMarket-Universal.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:780) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'colorgive' in plugin ChatColor v2.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at hu.infinityhosting.bukkit.managers.PurchaseManager.onPurchaseProcessing(PurchaseManager.java:126) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	... 11 more
Caused by: java.lang.NullPointerException
	at main.ColorGiveCommand1.onCommand(ColorGiveCommand1.java:169) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	at hu.infinityhosting.bukkit.managers.PurchaseManager.onPurchaseProcessing(PurchaseManager.java:126) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.jar:git-PaperSpigot-60136e7-18fbb24]
	... 11 more

**Comment by diecode** [comment]
Kellene némi részlet. Ha folyamatosan írja a hibát, minden parancs lekérésnél, akkor a debug bekapcsolása után az információ a konzolból a hiba előtt. A hibából arra következtetek, hogy egy másik plugin (ColorGive paranccsal rendelkező) okozza a hibát, annak a parancsa nem létezik vagy hibásan van megadva.

**Comment by andris155** [comment]
Csak ezt az egy hibakódot írta ma ha jól emlékszem 2-3x.

**Comment by andris155** [comment]
És ahogy írja is a játékos nem volt online mégis lefutatta ezt az egy db. parancsot annyiszor. Egyébként a parancs csak online játékossal megy, ha jól láttam az volt a hibák alján, hogy a colorgive csak online játékossal megy, ő meg nem volt az.

**Comment by diecode** [comment]
Be van állítva az online szükséglet az item megvásárlásához?

**Comment by andris155** [comment]
A parancs egyébként úgy is van beállítva, hogy csak akkor fusson le, ha játékos online.

**Comment by andris155** [comment]
![screenshot_20151216-000114](https://cloud.githubusercontent.com/assets/8324198/11826869/2865d6ba-a388-11e5-921a-7601ec120dff.png)

**Comment by andris155** [comment]
"Gida legutoljára 1 hónap 24 nap 4 óra-ja/-e volt fent a szerveren."

**Comment by diecode** [comment]
Akkor kérnék egy debug üzenetet a parancs lefutásokról ha van köztük ilyen termék valamint a termék parancsát ami a minemarketbe van írva

**Comment by diecode** [comment]
No megtaláltam a hiba okát, amiben egy kicsit többen is hibásak vagyunk.

A szerveren valóban nem volt elérhető "Gida" nevű játékos, viszont "Gida4" igen. A vásárlást "Gida" nevezetű felhasználó végezte és a rendszer is ezt tárolta, viszont:

- A Bukkit tartalmaz parancs és játékos név kiegészítő lehetőségeket, így ha a plugin "Gidá"-ra keres a Gida4 is találat lesz
- A MineMarket erre a rendszerre hagyatkozott, így tovább engedte a Gida felhasználó keresésekor a Bukkit által vissza adott Gida4 játékos elérhetősége esetén is
- A ColorChat pluginotok, másféleképpen ellenőrzi a játékos elérhetőségét ( helyesen ) viszont, nem szakítja meg a folyamatot, ha nem elérhető a játékos, ezért kaptatok hibaüzenetet.

A hibát orvosoltam a MineMarket pluginban, többen nem szabad, hogy előforduljon ilyen eset, teszteltem. A plugin két szerver újra indítás után ott lesz a szervereteken frissítés formájában, vagy letölthetitek a MineMarket oldaláról.

**Comment by andris155** [comment]
Köszönjük!
