### ISSUE TITLE
MineMarket plugin hiba.

### ISSUE THREAD

**Issue by andris155** [InfinityHosting/MineMarket-Issue#35]
```
[15:47:12] [pool-174-thread-1/WARN]: [Fatal Error] :1:50: White spaces are required between publicId and systemId.

[15:47:12] [pool-173-thread-1/WARN]: [Fatal Error] :1:50: White spaces are required between publicId and systemId.

[15:47:12] [Craft Scheduler Thread - 4174/WARN]: java.util.concurrent.ExecutionException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at java.util.concurrent.FutureTask.report(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at java.util.concurrent.FutureTask.get(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at hu.infinityhosting.bukkit.Settings$LicenseProcessor$1.run(Settings.java:136)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:71)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:12)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4174/WARN]: 	... 3 more
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: java.util.concurrent.ExecutionException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at java.util.concurrent.FutureTask.report(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at java.util.concurrent.FutureTask.get(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at hu.infinityhosting.bukkit.managers.PurchaseManager$PurchaseProcessor$1.run(PurchaseManager.java:171)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:71)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:12)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:47:12] [Craft Scheduler Thread - 4159/WARN]: 	... 3 more
```

**Comment by diecode** [comment]
Ez a hiba minden bizonnyal abból fakad, hogy a plugin képtelen letölteni a szükséges adatokat a DDoS támadás miatt. Ha a letöltés félbeszakad, akkor a bejövő adat formázása szétesik, ezért nem tudja feldolgozni azt.

**Comment by andris155** [comment]
Értem
